SET SQL_SAFE_UPDATES = 0;
CREATE TABLE `utubeauthors` ( 
`authorID` varchar(200) NOT NULL, 
`fname` varchar(100) DEFAULT NULL, 
`lname` varchar(100) DEFAULT NULL, 
`fullname` varchar(200) DEFAULT NULL, 
`title` varchar(500) DEFAULT NULL, 
`content` varchar(5000) DEFAULT NULL,
`location` varchar(10) DEFAULT NULL,
`published` varchar(50) DEFAULT NULL,
`views_count` int(11) DEFAULT NULL,
`subscribers_count` int(11) DEFAULT NULL,
`videos_watch_count` int(11) DEFAULT NULL,
`totalUploadViews` int(11) DEFAULT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;